Deal with race condition.
PROBLEM: it seems there is a race condition as with `[tokio::test]`
I get the following error:

failures:

---- nullifiers_merkle_tree::tests::test_hash stdout ----
Sent funding tx to deployer
thread 'nullifiers_merkle_tree::tests::test_hash' panicked at 'called `Result::unwrap()` on an `Err` value: AbiError(DecodingError(InvalidName("please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist")))', src/nullifiers_merkle_tree/mod.rs:43:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    nullifiers_merkle_tree::tests::test_hash

test result: FAILED. 13 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.41s

error: test failed, to rerun pass '--lib'

SOLUTION: removing `[tokio::test]` is enough.
Yet we should understand what is going on and review the others tests.